package main

import (
	"fmt"
	"os"
	"strings"
	"testing"
)

func TestOpen(t *testing.T) {
	dir, err := os.ReadDir("fc-lang")
	if err != nil {
		t.Fatal(err)
	}

	expectedNumberOfLines := map[string]int{
		"aa.orth":       12,
		"ab.orth":       13,
		"af.orth":       19,
		"agr.orth":      3,
		"ak.orth":       23,
		"am.orth":       36,
		"an.orth":       16,
		"anp.orth":      4,
		"ar.orth":       2,
		"as.orth":       14,
		"ast.orth":      20,
		"av.orth":       67,
		"ay.orth":       10,
		"ayc.orth":      6,
		"az_az.orth":    16,
		"az_ir.orth":    15,
		"ba.orth":       19,
		"be.orth":       5,
		"bem.orth":      2,
		"ber_dz.orth":   13,
		"ber_ma.orth":   16,
		"bg.orth":       6,
		"bh.orth":       4,
		"bhb.orth":      4,
		"bho.orth":      4,
		"bi.orth":       8,
		"bin.orth":      28,
		"bm.orth":       10,
		"bn.orth":       13,
		"bo.orth":       8,
		"br.orth":       14,
		"brx.orth":      16,
		"bs.orth":       12,
		"bua.orth":      70,
		"byn.orth":      28,
		"ca.orth":       24,
		"ce.orth":       67,
		"ch.orth":       8,
		"chm.orth":      76,
		"chr.orth":      1,
		"ckb.orth":      18,
		"cmn.orth":      13063,
		"co.orth":       34,
		"crh.orth":      15,
		"cs.orth":       32,
		"csb.orth":      15,
		"cu.orth":       15,
		"cv.orth":       74,
		"cy.orth":       28,
		"da.orth":       20,
		"de.orth":       9,
		"doi.orth":      12,
		"dsb.orth":      32,
		"dv.orth":       3,
		"dz.orth":       8,
		"ee.orth":       27,
		"el.orth":       5,
		"en.orth":       14,
		"eo.orth":       8,
		"es.orth":       16,
		"et.orth":       14,
		"eu.orth":       6,
		"fa.orth":       14,
		"fat.orth":      23,
		"ff.orth":       11,
		"fi.orth":       12,
		"fil.orth":      12,
		"fj.orth":       2,
		"fo.orth":       18,
		"fr.orth":       34,
		"fur.orth":      12,
		"fy.orth":       25,
		"ga.orth":       30,
		"gd.orth":       20,
		"gez.orth":      28,
		"gl.orth":       16,
		"gn.orth":       20,
		"gu.orth":       13,
		"gv.orth":       4,
		"ha.orth":       9,
		"hak.orth":      13063,
		"haw.orth":      8,
		"he.orth":       1,
		"hi.orth":       4,
		"hif.orth":      4,
		"hne.orth":      4,
		"ho.orth":       2,
		"hr.orth":       7,
		"hsb.orth":      12,
		"ht.orth":       6,
		"hu.orth":       18,
		"hy.orth":       2,
		"hz.orth":       5,
		"ia.orth":       2,
		"id.orth":       4,
		"ie.orth":       14,
		"ig.orth":       8,
		"ii.orth":       1,
		"ik.orth":       68,
		"io.orth":       2,
		"is.orth":       20,
		"it.orth":       18,
		"iu.orth":       48,
		"ja.orth":       2314,
		"jv.orth":       4,
		"ka.orth":       1,
		"kaa.orth":      78,
		"kab.orth":      13,
		"ki.orth":       6,
		"kj.orth":       2,
		"kk.orth":       8,
		"kl.orth":       29,
		"km.orth":       5,
		"kn.orth":       12,
		"ko.orth":       2442,
		"kok.orth":      4,
		"kr.orth":       5,
		"ks.orth":       25,
		"ku_am.orth":    61,
		"ku_iq.orth":    18,
		"ku_ir.orth":    18,
		"ku_tr.orth":    11,
		"kum.orth":      66,
		"kv.orth":       70,
		"kw.orth":       8,
		"kwm.orth":      2,
		"ky.orth":       70,
		"la.orth":       7,
		"lah.orth":      19,
		"lb.orth":       25,
		"lez.orth":      67,
		"lg.orth":       3,
		"li.orth":       12,
		"lij.orth":      23,
		"ln.orth":       19,
		"lo.orth":       17,
		"lt.orth":       11,
		"lv.orth":       15,
		"lzh.orth":      13063,
		"mag.orth":      4,
		"mai.orth":      4,
		"mfe.orth":      34,
		"mg.orth":       6,
		"mh.orth":       12,
		"mhr.orth":      3,
		"mi.orth":       8,
		"miq.orth":      21,
		"mjw.orth":      14,
		"mk.orth":       16,
		"ml.orth":       10,
		"mn_cn.orth":    5,
		"mn_mn.orth":    5,
		"mni.orth":      19,
		"mnw.orth":      5,
		"mo.orth":       11,
		"mr.orth":       4,
		"ms.orth":       2,
		"mt.orth":       18,
		"my.orth":       5,
		"na.orth":       9,
		"nan.orth":      13077,
		"nb.orth":       20,
		"nds.orth":      9,
		"ne.orth":       15,
		"ng.orth":       2,
		"nhn.orth":      18,
		"niu.orth":      19,
		"nl.orth":       32,
		"nn.orth":       16,
		"no.orth":       20,
		"nqo.orth":      1,
		"nr.orth":       2,
		"nso.orth":      7,
		"nv.orth":       17,
		"ny.orth":       3,
		"oc.orth":       20,
		"om.orth":       2,
		"or.orth":       13,
		"os.orth":       66,
		"ota.orth":      9,
		"pa.orth":       15,
		"pa_pk.orth":    19,
		"pap_an.orth":   14,
		"pap_aw.orth":   4,
		"pes.orth":      14,
		"pl.orth":       12,
		"prs.orth":      14,
		"ps_af.orth":    20,
		"ps_pk.orth":    20,
		"pt.orth":       32,
		"qu.orth":       5,
		"quz.orth":      5,
		"raj.orth":      4,
		"rif.orth":      25,
		"rm.orth":       16,
		"rn.orth":       2,
		"ro.orth":       8,
		"ru.orth":       3,
		"rw.orth":       2,
		"sa.orth":       4,
		"sah.orth":      76,
		"sat.orth":      16,
		"sc.orth":       12,
		"sco.orth":      5,
		"sd.orth":       22,
		"se.orth":       10,
		"sel.orth":      66,
		"sg.orth":       16,
		"sgs.orth":      18,
		"sh.orth":       36,
		"shn.orth":      5,
		"shs.orth":      20,
		"si.orth":       13,
		"sid.orth":      33,
		"sk.orth":       27,
		"sl.orth":       12,
		"sm.orth":       3,
		"sma.orth":      10,
		"smj.orth":      10,
		"smn.orth":      13,
		"sms.orth":      21,
		"sn.orth":       2,
		"so.orth":       2,
		"sq.orth":       6,
		"sr.orth":       10,
		"ss.orth":       2,
		"st.orth":       2,
		"su.orth":       4,
		"sv.orth":       18,
		"sw.orth":       2,
		"syr.orth":      2,
		"szl.orth":      24,
		"ta.orth":       15,
		"tcy.orth":      12,
		"te.orth":       11,
		"tg.orth":       78,
		"th.orth":       2,
		"the.orth":      4,
		"ti_er.orth":    28,
		"ti_et.orth":    33,
		"tig.orth":      24,
		"tk.orth":       13,
		"tl.orth":       12,
		"tn.orth":       7,
		"to.orth":       3,
		"tpi.orth":      14,
		"tr.orth":       20,
		"ts.orth":       2,
		"tt.orth":       76,
		"tw.orth":       23,
		"ty.orth":       10,
		"tyv.orth":      70,
		"ug.orth":       18,
		"uk.orth":       9,
		"und_zmth.orth": 115,
		"und_zsye.orth": 69,
		"unm.orth":      14,
		"ur.orth":       19,
		"uz.orth":       2,
		"ve.orth":       7,
		"vi.orth":       26,
		"vo.orth":       12,
		"vot.orth":      10,
		"wa.orth":       20,
		"wae.orth":      9,
		"wal.orth":      33,
		"wen.orth":      15,
		"wo.orth":       15,
		"xh.orth":       2,
		"yap.orth":      8,
		"yi.orth":       1,
		"yo.orth":       55,
		"yue.orth":      1083,
		"yuw.orth":      14,
		"za.orth":       2,
		"zh_cn.orth":    6765,
		"zh_hk.orth":    1083,
		"zh_mo.orth":    1083,
		"zh_sg.orth":    6765,
		"zh_tw.orth":    13063,
		"zu.orth":       2,
	}

	for _, file := range dir {
		if !strings.HasSuffix(file.Name(), "orth") {
			continue
		}
		lines := openOrthFile("fc-lang", file.Name())
		if expectedNumberOfLines[file.Name()] != len(lines) {
			t.Fatal(file.Name())
		}
	}
}

func TestParse(t *testing.T) {
	l := scanOrthFiles()
	if len(l) != 283 {
		t.Fatal(len(l))
	}

	fmt.Println(printLangTables(l))
}
