on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

name: build_linux

jobs:
  release-linux-amd64_x11:
    name: release linux/amd64 X11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: linux
          goarch: amd64
          release_tag: x11
          pre_command: "apt-get -y update ; apt-get -y upgrade ; apt-get -y  install libgl1-mesa-dev xorg-dev"
          binary_name: GopherLetics_Linux_AMD64_X11
  release-linux-amd64_wayland:
    name: release linux/amd64 Wayland
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: linux
          goarch: amd64
          release_tag: wayland
          pre_command: "apt-get -y update ; apt-get -y upgrade ; apt-get install -y libgl1-mesa-dev xorg-dev libwayland-dev"
          build_flags: -tags wayland
          binary_name: GopherLetics_Linux_AMD64_Wayland
