on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

name: build_mac

jobs:
  release-mac:
    name: release darwin/amd64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: darwin
          goarch: amd64
          pre_command: "xcode-select --install"
          binary_name: GopherLetics_Darwin_AMD64
