on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

name: build_windwos

jobs:
  release-windows-amd64:
    name: release linux/amd64 X11
    runs-on: winndows-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-go@v4
      #  with:
      #    check-latest: true
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: windows
          goarch: amd64
          binary_name: GopherLetics_Windows_AMD64
