on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

name: build_linux

jobs:
  release-linux-amd64_x11:
    name: release linux/amd64 X11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: linux
          goarch: amd64
          pre_command: "apt-get -y update ; apt-get -y upgrade ; apt-get -y install alsa-utils alsa-tools alsamixer libgl1-mesa-dev xorg-dev"
          binary_name: GopherLetics_Linux_AMD64_X11
  release-linux-amd64_wayland:
    name: release linux/amd64 Wayland
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: linux
          goarch: amd64
          pre_command: "apt-get -y update ; apt-get -y upgrade ; apt-get -y install alsa-utils alsa-tools alsamixer libgl1-mesa-dev xorg-dev libwayland-dev libxkbcommon-dev qtwayland5 libwayland-egl-backend-dev libnvidia-egl-wayland-dev libegl1-mesa-dev"
          build_flags: -tags wayland
          binary_name: GopherLetics_Linux_AMD64_Wayland
