on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

name: build_windows

jobs:
  release-windows-amd64:
    name: release windows/amd64
    runs-on: winndows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.BUILD }}
          goos: windows
          goarch: amd64
          binary_name: GopherLetics_Windows_AMD64
